name: dev

spring:
  application:
    name: product-service
  datasource:
    url: jdbc:postgresql://pg-products:5432/product_db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: none
    defer-datasource-initialization: true
  sql:
    init:
      mode: always

eureka:
  client:
    fetch-registry: true
    registry-with-eureka: true
    service-url:
      defaultZone: http://eurekaservice:8761/eureka
